export class Sehir{
  [x: string]: any;
   id:number|any;
   name:string;
  firebaseKey:string
   mekanlar:{
    mekan1:{
      id:number|any,
      name:string,
      description:string,
      imgUrl:string
      categoryId:number;
      latitude:string;
      longitude:string;
    },
    mekan2:{
      id:number|any,
      name:string,
      description:string,
      imgUrl:string
      categoryId:number;
      latitude:string;
      longitude:string;
    },
    mekan3:{
      id:number|any,
      name:string,
      description:string,
      imgUrl:string
      categoryId:number;
      latitude:string;
      longitude:string;
    },
    mekan4:{
      id:number|any,
      name:string,
      description:string,
      imgUrl:string
      categoryId:number;
      latitude:string;
      longitude:string;
    },
    mekan5:{
      id:number|any,
      name:string,
      description:string,
      imgUrl:string
      categoryId:number;
      latitude:string;
      longitude:string;
    },
   }
}
